### ISSUE TITLE
Crashing in kern_utils.m/kexecute.c on 11.3.1

### ISSUE THREAD

**Issue by yo-bur** [jakeajames/multi_path#1]
line inside `kern_utils.m` crashes: ```uint64_t context = zm_fix_addr(kexecute(ksym_vfs_context_current + kslide, 1, 0, 0, 0, 0, 0, 0));```

because of this line in `kexecute.c`:
```uint64_t returnval = IOConnectTrap6(user_client, 0, (uint64_t)(x1), (uint64_t)(x2), (uint64_t)(x3), (uint64_t)(x4), (uint64_t)(x5), (uint64_t)(x6));```.

Running on iPhone 6 11.3.1.
Offsets are:
`uint64_t ksym_vnode_lookup = 0xfffffff0071db710;`
`uint64_t ksym_vfs_context_current = 0xfffffff0071f9a04;`

**Comment by jakeajames** [comment]
are you sure the offsets are correct?

**Comment by raeedx** [comment]
b

**Comment by raeedx** [comment]
h

**Comment by aassq115533** [comment]
https://travis-ci.org/mrtazz/simplenote.py.svg?branch=master

**Comment by jakeajames** [comment]
Project deprecated, use rootlessJB & jelbrekLib
