### ISSUE TITLE
line inside kern_utils.m crashes: uint64_t context = zm_fix_addr(kexecute(ksym_vfs_context_current + kslide, 1, 0, 0, 0, 0, 0, 0));  because of this line in kexecute.c: uint64_t returnval = IOConnectTrap6(user_client, 0, (uint64_t)(x1), (uint64_t)(x2), (uint64_t)(x3), (uint64_t)(x4), (uint64_t)(x5), (uint64_t)(x6));.  Running on iPhone 6 11.3.1. Offsets are: uint64_t ksym_vnode_lookup = 0xfffffff0071db710; uint64_t ksym_vfs_context_current = 0xfffffff0071f9a04;  👍 4  

### ISSUE THREAD

**Issue by aassq115533** [jakeajames/multi_path#11]
line inside kern_utils.m crashes: uint64_t context = zm_fix_addr(kexecute(ksym_vfs_context_current + kslide, 1, 0, 0, 0, 0, 0, 0));

because of this line in kexecute.c:
uint64_t returnval = IOConnectTrap6(user_client, 0, (uint64_t)(x1), (uint64_t)(x2), (uint64_t)(x3), (uint64_t)(x4), (uint64_t)(x5), (uint64_t)(x6));.

Running on iPhone 6 11.3.1.
Offsets are:
uint64_t ksym_vnode_lookup = 0xfffffff0071db710;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9a04;

👍 4

**Comment by jakeajames** [comment]
Project deprecated, check rootlessJB & jelbrekLib
